/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-13: 16h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "zlog.h"
/* external codes at top */

#include "zlog.h"
#include <stdarg.h>

void zlog_handler (zlog_category_t *c, int level, char *fmt, ...) {
	va_list args;
	va_start (args, fmt);

	vzlog (
		c, 
		__FILE__, 
		sizeof(__FILE__) - 1, 
		__func__, 
		sizeof(__func__) - 1, 
		__LINE__, 
		level, 
		fmt, 
		args);

	va_end (args);
}

void dzlog_handler (int level, char *fmt, ...) {
	va_list args;
	va_start (args, fmt);

	vdzlog ( 
		__FILE__, 
		sizeof(__FILE__) - 1, 
		__func__, 
		sizeof(__func__) - 1, 
		__LINE__, 
		level, 
		fmt, 
		args);

	va_end (args);
}

int zlog_category_is_not_null (zlog_category_t *c) {
	return c != NULL;
}

void zlog_fini_empty () {}


/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
/* empty */
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/* static load function */

extern ats_void_type _2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2esats__staload (void) ;

ats_void_type
_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__staload () {
static int _2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__staload_flag = 0 ;
if (_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__staload_flag) return ;
_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__staload_flag = 1 ;

_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__dynload_flag ;

ats_void_type
_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__dynload () {
_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__dynload_flag = 1 ;
_2home_2hwwu_2Workspace_2ats_2dzlog_2zlog_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [zlog_dats.c] */
